[package]
name = "cas1"
version = "0.1.0"
edition = "2024"
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Implements a(n) (dis)assembler for the CAS1 assembly language."


[dependencies]
ast-toolkit2 = { git = "https://github.com/Lut99/ast-toolkit2-rs", features = ["macros", "nibble"] }


[features]
default = []
